query marketDetails($address: String!, $intervalUnit: OHLCVIntervalUnitInfo!, $startDate: Float!, $endDate: Float!) {
  market(address: $address) {
    name
    version
    address
    coin {
      address
      name
      decimals
      symbol
      logoURI
    }
    pc {
      address
      name
      decimals
      symbol
      logoURI
    }
    stats {
      vol24h
      vol7d
      price
    }
  }
  ohlcv(market: $address, intervalUnit: $intervalUnit, startDate: $startDate, endDate: $endDate) {
    open
    high
    low
    close
    volume
    interval
  }
}