{
  markets {
    name
    version
    address
    coin {
      address
      logoURI
    }
    pc {
      address
      logoURI
    }
    stats {
      vol24hUsd
      vol7dUsd
      priceUsd
      tvlUsd
    }
  }
}
