{
  markets {
    name
    version
    address
    coin {
      chainId
      address
      name
      decimals
      symbol
      logoURI
    }
    pc {
      chainId
      address
      name
      decimals
      symbol
      logoURI
    }
    stats {
      vol24h
      price
    }
  }
}
