query marketDetails($address: String!, $intervalUnit: OHLCVIntervalUnitInfo!, $startDate: Float!, $endDate: Float!) {
  market(address: $address) {
    name
    version
    address
    coin {
      address
      name
      decimals
      symbol
      logoURI
    }
    pc {
      address
      name
      decimals
      symbol
      logoURI
    }
    stats {
      vol24h
      vol7d
      vol24hUsd
      vol7dUsd
      price
      priceUsd
      tvlCoin
      tvlPc
      tvlUsd
    }
  }
  hourlyStats(market: $address) {
    tvl {
      tvlCoin
      tvlPc
    },
    ohlcv {
  		open
  		high
  		low
  		close
    	volume
      interval
    }
  }
}