query trades($address: String!) {
  trades(market: $address, limit: 500, maker: false) {
    market
    side
    price
    baseAmount
    quoteAmount
    feeAmount
    quoteAmountUsd
    account
    timestamp
    baseToken {
      symbol
      decimals
    }
    quoteToken {
      symbol
      decimals
    }
  }
}